#!/usr/bin/env node

import fs from "fs";
import path from "path";

const logFile = path.join(process.cwd(), "xavren-install.log");
const log = (msg) => {
  const timestamp = new Date().toISOString();
  const logMsg = `[${timestamp}] ${msg}\n`;
  try {
    fs.appendFileSync(logFile, logMsg);
  } catch (e) {
    // Ignore log file errors
  }
  console.error(msg);
};

function findProjectRoot(startDir) {
  let currentDir = startDir;
  const root = path.parse(currentDir).root;

  // Traverse up until we find node_modules in the path
  while (currentDir !== root) {
    if (currentDir.includes('node_modules')) {
      // Go up to parent of node_modules
      const parts = currentDir.split(path.sep);
      const nodeModulesIndex = parts.lastIndexOf('node_modules');
      if (nodeModulesIndex !== -1) {
        // Join everything before node_modules
        return parts.slice(0, nodeModulesIndex).join(path.sep);
      }
    }
    currentDir = path.dirname(currentDir);
  }

  return null;
}

function installPrePushHook() {
  log("=== Xavren Hook Installation ===");
  log(`📍 Script running from: ${process.cwd()}`);
  log(`👤 User: ${process.env.USER || process.env.USERNAME}`);
  log(`🔧 Node version: ${process.version}`);

  // Find the project root (parent of node_modules)
  const projectRoot = findProjectRoot(process.cwd());

  if (!projectRoot) {
    log("❌ Could not find project root (parent of node_modules).");
    return;
  }

  log(`✅ Found project root at: ${projectRoot}`);

  const gitDir = path.join(projectRoot, ".git");
  log(`🔍 Looking for .git at: ${gitDir}`);
  log(`📁 .git exists: ${fs.existsSync(gitDir)}`);

  if (!fs.existsSync(gitDir)) {
    log("❌ Not a Git repository. Skipping hook installation.");
    log("💡 This is normal if installing in a non-git project.");
    return;
  }

  const hookDir = path.join(gitDir, "hooks");
  const hookPath = path.join(hookDir, "pre-push");

  log(`📂 Hook directory: ${hookDir}`);
  log(`📄 Hook path: ${hookPath}`);

  // Check permissions
  try {
    fs.accessSync(gitDir, fs.constants.W_OK);
    log("✅ Write permission confirmed");
  } catch (err) {
    log(`❌ Permission error: ${err.message}`);
    log("Try running: sudo chown -R $USER .git");
    return;
  }

  // Create hooks directory
  if (!fs.existsSync(hookDir)) {
    try {
      fs.mkdirSync(hookDir, { recursive: true });
      log("📁 Created hooks directory");
    } catch (err) {
      log(`❌ Failed to create hooks dir: ${err.message}`);
      return;
    }
  }

  // Remove old hook
  if (fs.existsSync(hookPath)) {
    try {
      fs.unlinkSync(hookPath);
      log("♻️  Removed existing pre-push hook");
    } catch (unlinkErr) {
      log(`⚠️  Couldn't remove old hook: ${unlinkErr.message}`);
    }
  }

  const hookContent = `#!/bin/bash
# Auto-generated by xavren installer
echo "🚀 Running xavcli postinstall before git push..."
xavcli_postinstall || echo "⚠️ xavcli_postinstall failed, but continuing push..."
`;

  try {
    fs.writeFileSync(hookPath, hookContent, { encoding: "utf-8", mode: 0o755 });
    log("📝 Hook file written");
    
    if (fs.existsSync(hookPath)) {
      const stats = fs.statSync(hookPath);
      const isExecutable = (stats.mode & 0o111) !== 0;
      log(`✅ Pre-push hook installed successfully!`);
      log(`🔐 Executable: ${isExecutable}`);
      log(`📊 File size: ${stats.size} bytes`);
      log(`📍 Hook location: ${hookPath}`);
    } else {
      log("❌ Hook file was not created!");
    }
  } catch (err) {
    log(`❌ Write error: ${err.message}`);
    log(err.stack);
  }

  log("=== Installation Complete ===");
}

try {
  installPrePushHook();
} catch (err) {
  log(`❌ Fatal error: ${err.message}`);
  log(err.stack);
}
// #!/usr/bin/env node

// import fs from "fs";
// import path from "path";

// function installPrePushHook() {
//   console.log("🪝 Setting up xavren pre-push hook...");

//   const gitDir = path.resolve(process.cwd(), ".git");
//   const hookDir = path.join(gitDir, "hooks");
//   const hookPath = path.join(hookDir, "pre-push");

//   // 1️⃣ Check if we're in a Git repo
//   if (!fs.existsSync(gitDir)) {
//     console.log("❌ Not a Git repository. Skipping hook installation.");
//     return;
//   }

//   fs.mkdirSync(hookDir, { recursive: true });

//   // 2️⃣ Hook content — run xavcli_postinstall but never stop push
//   const hookContent = `#!/bin/bash
// # Auto-generated by xavren installer
// # This hook runs xavcli postinstall logic before pushing, but never aborts the push

// echo "🚀 Running xavcli postinstall before git push..."

// # Run postinstall CLI
// xavcli_postinstall || echo "⚠️ xavcli_postinstall failed, but continuing push..."
// `;

//   // 3️⃣ Write or overwrite the hook file
//   fs.writeFileSync(hookPath, hookContent, "utf-8");
//   fs.chmodSync(hookPath, 0o755);

//   console.log("✅ Pre-push hook installed successfully!");
// }

// try {
//   installPrePushHook();
// } catch (err) {
//   console.error("❌ Failed to install pre-push hook:", err);
// }
